### PR TITLE
73 sepia plugin

### PR DESCRIPTION
**Pull request by kondratowiczm**

### CODE REVIEW

**Comment by dkrawiec** [comment]
Looks fine. Would it be possible to add unit tests?

**Comment by kondratowiczm** [comment]
Might be difficult, different tools uses different sepia settings so it would be hard to compare result of this filter with filter from any other library and counting this manually does not sound good.

**Comment by dkrawiec** [comment]
Yeah, but writing assertions for small case like 2x2 with expected values will still be better than nothing.

**Comment by kondratowiczm** [comment]
I can calculate expected values for case 2x2 but I don't know how to test those steps and rest of things

**Comment by dkrawiec** [comment]
Work will be continued in dedicated feature branch in KiMage repository https://github.com/kmisztal/KiMage/tree/73-sepia-plugin

**Pull request closed without merging**
