### PR TITLE
Sharpen plugin

### PR DESCRIPTION
**Pull request by mchuck**

### CODE REVIEW

**Comment by dkrawiec** [comment]
As far as I remember we wanted to wrap AWT methods either with some class or lambda expression in order to avoid coupling between plugin implementations and AWT. Here we have direct invocations of AWT methods. This should be wrapped in imageprocessor-awt module and in plugins we should use the wrappers. @annadobrowolska am I correct?

**Comment by annaskulimowska** [comment]
Yes, there is the maven module for awt dependent code

-----Wiadomość oryginalna-----
Od: "Damian Krawiec" notifications@github.com
Wysłano: ‎2016-‎06-‎04 14:53
Do: "kmisztal/KiMage" KiMage@noreply.github.com
DW: "annadobrowolska" anna90dobrowolska@gmail.com; "Mention" mention@noreply.github.com
Temat: Re: [kmisztal/KiMage] Plugin (#82)

As far as I remember we wanted to wrap AWT methods either with some class or lambda expression in order to avoid coupling between plugin implementations and AWT. Here we have direct invocations of AWT methods. This should be wrapped in kimage-awt module and in plugins we should use the wrappers. @annadobrowolska am I correct?

**Comment by dkrawiec** [comment]
~~And I see that we have redundant converter committed here. I know this story depends on #66 for converters, but we don't want these changes here. Please wait for merge of #79 to master and then merge it here.~~

Now I see that it has the same hash id so it shouldn't be a problem.

**Comment by mchuck** [comment]
There is no merged AWT BufferedImage converter nor any of the current AWT methods. Writing them is not really the purpose of this issue and may mislead the other implementations of plugins, so I decided to do the necessary thing in here, merging the converter from another fork and doing the AWT methods inside the plugin. I'm not sure if we should open an another issue and make these methods in AWT module, telling everyone else to use it, or leave it like it is. Up to you, but there is really not so much time left.

**Comment by dkrawiec** [comment]
I think that it was decided that if some plugin needs methods from the AWT then this is also part of the story to implement wrappers in imageprocessor-awt. Please implement it that way. Don't worry about time, we have enough.

**Comment by mchuck** [comment]
Ok, we will change that with @osipam.

**Comment by dkrawiec** [comment]
Ok, but keep in mind that you shouldn't create circular dependencies between branches. Commit it to one, then merge to master and master with another branch

**Pull request closed without merging**
