### PR TITLE
[#33] Added GUI layout views and attached blank controllers.

### PR DESCRIPTION
**Pull request by tomczylok**
#33

### CODE REVIEW

**Comment by dkrawiec** [comment]
I'm not getting why we need 4 different classes which looks exactly the same. Couldn't it be done with one class definition and 4 instances? Does it really need so much of a boilerplate code? Or is this for future development? If so please add suitable comments to class definitions.

**Comment by tomczylok** [comment]
This is for future development. We need this way of dividing views into smaller parts, thus we need more controllers for that. I will add some comments to every controller.

**Comment by pchachaj** [comment]
There is some misspelling in your comments, beside that it's ok.

**Comment by pchachaj** [comment]
ok

**Pull request merged**
